services:
  postgres:
    image: postgres:17
    container_name: quiz_app_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminadmin
    ports:
      - "5432:5432"
    volumes:
      - quiz_app_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  quiz_app_postgres_data:
